name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
         severurl: https://index.docker.io/v1
         username: ${DOCKERHUB_USERNAME}
         password: ${DOCKERHUB_PASSWORD}

