name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2
       with:
          fetch-depth: 0
     - name: Login to Docker Hub
       if: ${{ github.event_name == 'push'}}
       uses: docker/login-action@v1
       with:
          username: ${DOCKERHUB_USERNAME}
          password: ${DOCKERHUB_PASSWORD}
